### Vetores

##### Exemplos de declarações de vetores
```{r}
vetorLogico   = c(TRUE, TRUE, FALSE, FALSE)
vetorInteiro  = c(10L, 50L, 60L, 5L)
vetorNumerico = c(55.6, 56.4, 23.3, 14.2)
vetorTexto    = c("Apple", "Samsung", "Microsoft", "BlackBerry")
vetorImaginar = c(1i, 22i, -5i, 88i)
```

##### Operações nos vetores
```{r}
vet = c(55.6, 56.4, 23.3, 14.2)
vet = vet * 2
vet
vet.valores = c(1,2,3,4,5,6,7)
sum(vet.valores) #soma
min(vet.valores) #mínimo
max(vet.valores) #máximo
mean(vet.valores) #média
median(vet.valores) #mediana
quantile(vet.valores) #quartis
```

##### Dando nome à posições nos vetores
```{r}
semana.int = c(1,2,3,4,5,6,7)
semana.str = c("Domingo", "Segunda", "Terça", "Quarta", "Quinta", "Sexta", "Sábado")
names(semana.int) <- semana.str
semana.int
```

##### Subsets nos vetores
```{r}
vetA_I = c("A","B","C","D","E","F","G","H","I")
vetA_I[2] #Posição 2
vetA_I[1:3] #Posição 1 a 3
vetA_I[c(-1, -2)] #Sem as posições 1 e 2
vetA_I[c(FALSE, TRUE, FALSE, TRUE, TRUE, FALSE)] #Com um vetor lógico
```

##### Lista com Vetores
```{r}
#Criando uma lista com vetores dentro
lista <- list(vetorLogico, vetorInteiro, vetorNumerico, vetorTexto, vetorImaginar)
```

```{r}
#Criando um dataframe a partir da lista
df = data.frame(lista)
df
```